//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inside.Xamarin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inside.Xamarin.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been successfully changed.
        /// </summary>
        public static string ChangePasswordSuccessAlert {
            get {
                return ResourceManager.GetString("ChangePasswordSuccessAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy {0} coins!.
        /// </summary>
        public static string CoinBuyConfirmAlert {
            get {
                return ResourceManager.GetString("CoinBuyConfirmAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You has purchase {0} more coins!.
        /// </summary>
        public static string CoinBuyCongratulationsAlert {
            get {
                return ResourceManager.GetString("CoinBuyCongratulationsAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy now {0} CHF.
        /// </summary>
        public static string CoinBuyNow {
            get {
                return ResourceManager.GetString("CoinBuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password does not match the registered password.
        /// </summary>
        public static string EditProfileOldPasswordAlert {
            get {
                return ResourceManager.GetString("EditProfileOldPasswordAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been successfully changed.
        /// </summary>
        public static string EditProfileSuccessAlert {
            get {
                return ResourceManager.GetString("EditProfileSuccessAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string GeneralAccept {
            get {
                return ResourceManager.GetString("GeneralAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GeneralCancel {
            get {
                return ResourceManager.GetString("GeneralCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection and try again.
        /// </summary>
        public static string GeneralCheckInternetConnection {
            get {
                return ResourceManager.GetString("GeneralCheckInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm?.
        /// </summary>
        public static string GeneralConfirm {
            get {
                return ResourceManager.GetString("GeneralConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string GeneralCongratulations {
            get {
                return ResourceManager.GetString("GeneralCongratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string GeneralCreate {
            get {
                return ResourceManager.GetString("GeneralCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string GeneralEdit {
            get {
                return ResourceManager.GetString("GeneralEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string GeneralLogin {
            get {
                return ResourceManager.GetString("GeneralLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string GeneralNo {
            get {
                return ResourceManager.GetString("GeneralNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Error.
        /// </summary>
        public static string GeneralPasswordError {
            get {
                return ResourceManager.GetString("GeneralPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string GeneralRegister {
            get {
                return ResourceManager.GetString("GeneralRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string GeneralSave {
            get {
                return ResourceManager.GetString("GeneralSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        public static string GeneralServerError {
            get {
                return ResourceManager.GetString("GeneralServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string GeneralSuccess {
            get {
                return ResourceManager.GetString("GeneralSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string GeneralYes {
            get {
                return ResourceManager.GetString("GeneralYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upps Server is unreachable..
        /// </summary>
        public static string LoginErrorServerAlert {
            get {
                return ResourceManager.GetString("LoginErrorServerAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password..
        /// </summary>
        public static string LoginPasswordAlert {
            get {
                return ResourceManager.GetString("LoginPasswordAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an username..
        /// </summary>
        public static string LoginUserNameAlert {
            get {
                return ResourceManager.GetString("LoginUserNameAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password are incorrect..
        /// </summary>
        public static string LoginUserPasswordIncorrectAlert {
            get {
                return ResourceManager.GetString("LoginUserPasswordIncorrectAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string MasterItemChangePassword {
            get {
                return ResourceManager.GetString("MasterItemChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string MasterItemChangePasswordAlert {
            get {
                return ResourceManager.GetString("MasterItemChangePasswordAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string MasterItemChangePasswordHeaderAlert {
            get {
                return ResourceManager.GetString("MasterItemChangePasswordHeaderAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string MasterItemEditProfile {
            get {
                return ResourceManager.GetString("MasterItemEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your Profile..
        /// </summary>
        public static string MasterItemEditProfileAlert {
            get {
                return ResourceManager.GetString("MasterItemEditProfileAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string MasterItemEditProfileHeaderAlert {
            get {
                return ResourceManager.GetString("MasterItemEditProfileHeaderAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        public static string MasterItemLogout {
            get {
                return ResourceManager.GetString("MasterItemLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You has been logged out from the app..
        /// </summary>
        public static string MasterItemLogoutAlert {
            get {
                return ResourceManager.GetString("MasterItemLogoutAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged Out.
        /// </summary>
        public static string MasterItemLogoutHeaderAlert {
            get {
                return ResourceManager.GetString("MasterItemLogoutHeaderAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to load parking&apos;s categories..
        /// </summary>
        public static string ParkingCategoryLoadAlert {
            get {
                return ResourceManager.GetString("ParkingCategoryLoadAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to add a new parking..
        /// </summary>
        public static string ParkingCreateAddAlert {
            get {
                return ResourceManager.GetString("ParkingCreateAddAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose source to add the photo..
        /// </summary>
        public static string ParkingCreateAddPhotoHeaderAlert {
            get {
                return ResourceManager.GetString("ParkingCreateAddPhotoHeaderAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick From Gallery..
        /// </summary>
        public static string ParkingCreateAddPhotoOption1 {
            get {
                return ResourceManager.GetString("ParkingCreateAddPhotoOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take A Photo From Camera..
        /// </summary>
        public static string ParkingCreateAddPhotoOption2 {
            get {
                return ResourceManager.GetString("ParkingCreateAddPhotoOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pick photo available..
        /// </summary>
        public static string ParkingCreatePickPhotoAlert {
            get {
                return ResourceManager.GetString("ParkingCreatePickPhotoAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Photo error.
        /// </summary>
        public static string ParkingCreatePickPhotoHeaderAlert {
            get {
                return ResourceManager.GetString("ParkingCreatePickPhotoHeaderAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photo is not available or is not soported.
        /// </summary>
        public static string ParkingCreateTakePhotoAlert {
            get {
                return ResourceManager.GetString("ParkingCreateTakePhotoAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo error.
        /// </summary>
        public static string ParkingCreateTakePhotoHeaderAlert {
            get {
                return ResourceManager.GetString("ParkingCreateTakePhotoHeaderAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to add a new parking.
        /// </summary>
        public static string ParkingEditAlert {
            get {
                return ResourceManager.GetString("ParkingEditAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to create a parking.
        /// </summary>
        public static string ParkingInfoRentAlert {
            get {
                return ResourceManager.GetString("ParkingInfoRentAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to load parking&apos;s types..
        /// </summary>
        public static string ParkingTypeLoadAlert {
            get {
                return ResourceManager.GetString("ParkingTypeLoadAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to create the user..
        /// </summary>
        public static string RegisterAddUser {
            get {
                return ResourceManager.GetString("RegisterAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is empty.
        /// </summary>
        public static string RegisterEmailEmptyAlert {
            get {
                return ResourceManager.GetString("RegisterEmailEmptyAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your confirmed password are incorrect or maybe is empty..
        /// </summary>
        public static string RegisterPasswordConfAlert {
            get {
                return ResourceManager.GetString("RegisterPasswordConfAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register successfully.
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is empty.
        /// </summary>
        public static string RegisterUserEmptyAlert {
            get {
                return ResourceManager.GetString("RegisterUserEmptyAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COIN.
        /// </summary>
        public static string TabsCoin {
            get {
                return ResourceManager.GetString("TabsCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string TabsHome {
            get {
                return ResourceManager.GetString("TabsHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent By Hours.
        /// </summary>
        public static string TabsRentByHours {
            get {
                return ResourceManager.GetString("TabsRentByHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent For Month.
        /// </summary>
        public static string TabsRentForMonth {
            get {
                return ResourceManager.GetString("TabsRentForMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want add a Parking?.
        /// </summary>
        public static string XamlCreateParkingPopUpLabel {
            get {
                return ResourceManager.GetString("XamlCreateParkingPopUpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string XamlEditNamePlaceholder {
            get {
                return ResourceManager.GetString("XamlEditNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string XamlEditProfileNewPasswordLabel {
            get {
                return ResourceManager.GetString("XamlEditProfileNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new password.
        /// </summary>
        public static string XamlEditProfileNewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("XamlEditProfileNewPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string XamlEditProfileOldPasswordLabel {
            get {
                return ResourceManager.GetString("XamlEditProfileOldPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the old password.
        /// </summary>
        public static string XamlEditProfileOldPasswordPlaceholder {
            get {
                return ResourceManager.GetString("XamlEditProfileOldPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string XamlLoginPasswordLabel {
            get {
                return ResourceManager.GetString("XamlLoginPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password....
        /// </summary>
        public static string XamlLoginPasswordPlaceholder {
            get {
                return ResourceManager.GetString("XamlLoginPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string XamlLoginRemeberMeText {
            get {
                return ResourceManager.GetString("XamlLoginRemeberMeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string XamlLoginUsernameLabel {
            get {
                return ResourceManager.GetString("XamlLoginUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username....
        /// </summary>
        public static string XamlLoginUsernamePlaceholder {
            get {
                return ResourceManager.GetString("XamlLoginUsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking Category:.
        /// </summary>
        public static string XamlParkingCreateCategoryLabel {
            get {
                return ResourceManager.GetString("XamlParkingCreateCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Category.
        /// </summary>
        public static string XamlParkingCreateCategoryPicker {
            get {
                return ResourceManager.GetString("XamlParkingCreateCategoryPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        public static string XamlParkingCreatePriceLabel {
            get {
                return ResourceManager.GetString("XamlParkingCreatePriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Price.
        /// </summary>
        public static string XamlParkingCreatePricePlaceholder {
            get {
                return ResourceManager.GetString("XamlParkingCreatePricePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking Type:.
        /// </summary>
        public static string XamlParkingCreateTypeLabel {
            get {
                return ResourceManager.GetString("XamlParkingCreateTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Parking Type.
        /// </summary>
        public static string XamlParkingCreateTypePicker {
            get {
                return ResourceManager.GetString("XamlParkingCreateTypePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Date:.
        /// </summary>
        public static string XamlParkingInfoRentDateLabel {
            get {
                return ResourceManager.GetString("XamlParkingInfoRentDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent From:.
        /// </summary>
        public static string XamlParkingInfoRentFromLabel {
            get {
                return ResourceManager.GetString("XamlParkingInfoRentFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent:.
        /// </summary>
        public static string XamlParkingInfoRentLabel {
            get {
                return ResourceManager.GetString("XamlParkingInfoRentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent To:.
        /// </summary>
        public static string XamlParkingInfoRentToLabel {
            get {
                return ResourceManager.GetString("XamlParkingInfoRentToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password:.
        /// </summary>
        public static string XamlRegisterConfimPasswordLabel {
            get {
                return ResourceManager.GetString("XamlRegisterConfimPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password....
        /// </summary>
        public static string XamlRegisterConfimPasswordPlaceholder {
            get {
                return ResourceManager.GetString("XamlRegisterConfimPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string XamlRegisterEmailLabel {
            get {
                return ResourceManager.GetString("XamlRegisterEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address....
        /// </summary>
        public static string XamlRegisterEmailPlaceholder {
            get {
                return ResourceManager.GetString("XamlRegisterEmailPlaceholder", resourceCulture);
            }
        }
    }
}
